version: "3.4"

services:
    crawl-postgres:
        image: postgres:13.1
        container_name: insta-crawler-posgres
        restart: always
        ports:
            - "5437:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres